### PR TITLE
Add some error checking. So we dont brick devices. rhcp011235@me.com

### PR DESCRIPTION
**Pull request by rhcp011235**

### CODE REVIEW

**Comment by rhcp011235** [comment]
Tested this and its working for the partial unlock that I reversed and made open source as well :)

**Comment by rhcp011235** [comment]
Why would this fail on a pre-rooted version? as i am checking the ro.build (and the title can be changed)

**Comment by androidrbox** [comment]
root@android:/ # grep ro.build.version.incremental= /system/build.prop  
ro.build.version.incremental=51.1.4.1_user_514013920

And the unlock works just fine.

**Comment by rhcp011235** [comment]
what channel are you on? on irc? i can't find you. I'm on Freenode

**Comment by rhcp011235** [comment]
ok i see what you mean.

**Pull request closed without merging**
